version: '3'

services:
  terraform:
    image: hashicorp/terraform:1.2.5
    volumes:
      - ./.aws:/root/.aws
      - ./terraform:/app/
    working_dir: /app/
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-localstack}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
    networks: [localstack-network]
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,iam,kinesis,lambda # 使いたいAWSサービスカンマ区切りで設定する
      - DEFAULT_REGION=ap-northeast-1 # リージョンを設定
      - DATA_DIR=/tmp/localstack/data # データ保存するディレクトリ
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
    volumes:
      - ./localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - 4566:4566 # サービスへのアクセスポートは4566
    networks: [localstack-network]
networks:
  localstack-network:
    driver: bridge
